name: Playwright Allure Report with Github OIDC Connect integrated with AWS s3 bucket
"on":
  push:
    branches:
      - main

permissions:
    id-token: write
    contents: read

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test::all
      - name: Generate Allure Report
        run: npm run generate::allure-report
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
          retention-days: 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        if: always()
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload to S3 bucket
        id: S3
        if: always()
        env:
          REPORT_DIR: playwright-allure-report-${{ github.run_id }}
        run: |
            echo "REPORT_DIR=$REPORT_DIR" >> $GITHUB_ENV
            aws s3 cp playwright-allure-report/. s3://${{ vars.AWS_S3_BUCKET }}/$REPORT_DIR --recursive

      - name: Create URL file
        if: always()
        run: |
            REPORT_URL="https://${{ vars.AWS_S3_BUCKET }}.s3.${{ vars.AWS_REGION }}.amazonaws.com/${{ env.REPORT_DIR }}/index.html"
            echo $REPORT_URL > url.txt
            echo "Report URL: $REPORT_URL"

      - name: Setup Job Summary
        if: always()
        run: |
            REPORT_URL="https://${{ vars.AWS_S3_BUCKET }}.s3.${{ vars.AWS_REGION }}.amazonaws.com/${{ env.REPORT_DIR }}/index.html"
            echo " 🔗 [View Playwright Report]($REPORT_URL)" >> $GITHUB_STEP_SUMMARY